### ISSUE TITLE
03-Creating-Basic-Stimuli tutorial not working

### ISSUE THREAD

**Issue by nbonacchi** [amansaleem/BonVision#3]
Just following the gratings example from https://amansaleem.github.io/BonVision/pages/03-Creating-Basic-Stimuli/#
yields a workflow that fails to open a shader window. 
Looking at the examples of the repo in the primitives folder I find that the CreateWindow--BonVisionResources--LoadResources branch is missing from the explanation of the tutorial.
It would be useful, especially for new users, to be able to follow something that works so they can build on it.

**Comment by amansaleem** [comment]
Thanks for pointing this out. 
Yes - the basic structure has changed since that document was written. 

Every workflow now needs to have:
Renderframe--BonVisionResources--LoadResources 
as the starting point.

I will update the site asap.

**Comment by amansaleem** [comment]
I've updated the page. The instructions should now be correct. Let me know if you have any other issues.
