### ISSUE TITLE
Examples folder

### ISSUE THREAD

**Issue by jsiegle** [amansaleem/BonVision#6]
The examples in this repo are super helpful, thanks for including those!

I have two requests:

Is it possible to update the example .bonsai files to be compatible with the latest version of the software? The demo workflows seem to run just fine, but it still displays a warning when loading them. 

Can the examples be saved in uncompressed folders? It's annoying to have to unzip them all prior to use.

**Comment by glopesdev** [comment]
Agree with both issues, also saving them uncompressed will be more convenient for versioning.
